### ISSUE TITLE
API Planning

### ISSUE THREAD

**Issue by csjoblom** [csjoblom/tao-redhat#1]
How are we going to interact with our API? What endpoints do we need for our functionality?

**Comment by csjoblom** [comment]
This will be the main thread for our api planning, we'll create tickets based on discussions in here.

**Comment by antonioortegajr** [comment]
From mobile app to API endpoints

Mobile application will need to POST new users to the API. 

Route:
     /newuser

Parameters:
    phone = phone number of the reporter

Return:
        {
    "user_id": 1
}

Mobile application will need to POST new reports to the API. 

Route: 
    /report

Parameters:
    lat = the latitude
    lng = the longitude
    phone = phone number of the reporter (might be in the db but people do change numbers and phones)
    id = the id of the reporter

Return:
    {
    "case_id": 1
}

Mobile application will need to POST follow up reports to the API. (this might be better handled as a webview to a html5 form online.)

Route:
    /followup

Parameters:
    lat = the latitude
    lng = the longitude
    phone = phone number of the reporter (might be in the db but people do change numbers and phones)
    id = the id of the reporter
    case = case id from initial report
    info = the information the reporter has on the report

photos/video will need to be accepted as well.

Return
     {
    "case_id": 1,
    "updated": "y"
}

**Comment by csjoblom** [comment]
Heres what I'm thinking as far as modeling:

Report
- ReportID
- Type
- Impact
- AdditionalInfo
  - whatever additional fields we decide to provide for input
- Location
  - x,y,z
  - whatever other meta that can be instantly derived from the data
  - google map search url, mapimage
- SnapImage
  - resourceurl
  - meta
- Meta
  - whatever permission level details, we have to ask the phone
  - created/updated/logging/etc
  - view count, calculated metas
- Permissions

User (whatever the standard for user model is nowadays)
- UserID
- Username
- Password
- Email
- Phone
- OAuth
- Permissions
- Reports
- Subscriptions
- Meta
- Profile
  - Personal information
- Settings
- SoftDelete

We'll need basic CRUD for all of these (maybe not delete)
/users/:id
/users/:id/update
/users/create

/profile/:id
/profile/:id/update
/profile/create

/auth/login
/auth/logout
/auth/resetpassword

/reports/:id
/reports/:id/update
/reports/create
/reports
